#! /usr/bin/env zsh

function main TRAPEXIT {

  cd {{ project_name }}/build-debug

  cmake -B . -S ../source --preset default-ninja
  cmake --build .
  ln --symbolic --relative {{ project_name }} ../bin/

  cd ../source

  docker image build --tag {{ project_name }}:latest --file Dockerfile .
}

